[profile.default]
src = "."
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
base = "https://mainnet.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
